<#
.SYNOPSIS
    Rollback tool for file organizer operations (PowerShell)
.DESCRIPTION
    Reads the operation log generated by organize.ps1 and reverses file moves.
    Cleans up empty auto-created folders after rollback.
.PARAMETER Command
    Available commands: rollback-all, rollback-single, list-logs
.PARAMETER LogPath
    Path to the operation log JSON file (for rollback-all / rollback-single)
.PARAMETER FileName
    Name of the file to rollback (for rollback-single)
.PARAMETER TargetDir
    Directory that was organized (for list-logs)
.PARAMETER DryRun
    Preview without executing
#>
param(
    [Parameter(Mandatory=$true, Position=0)]
    [ValidateSet("rollback-all","rollback-single","list-logs")]
    [string]$Command,

    [Parameter(Position=1)]
    [string]$LogPath,

    [string]$FileName,

    [string]$TargetDir,

    [switch]$DryRun
)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8

function Invoke-RollbackAll {
    param([string]$LogFilePath, [bool]$IsDryRun)

    $logFile = Resolve-Path -LiteralPath $LogFilePath -ErrorAction Stop
    if (-not (Test-Path -LiteralPath $logFile)) {
        @{ error = "Log file not found: $logFile" } | ConvertTo-Json -Depth 5
        exit 1
    }

    $logContent = Get-Content -LiteralPath $logFile -Raw -Encoding UTF8 | ConvertFrom-Json

    $results = @{
        rollback_log    = $logFile.ToString()
        dry_run         = $IsDryRun
        restored        = @()
        failed          = @()
        cleaned_folders = @()
    }

    # Reverse operations in reverse order
    $ops = @($logContent.operations)
    [array]::Reverse($ops)

    foreach ($op in $ops) {
        if ($op.status -eq "dry_run") { continue }

        $dst = $op.destination_path
        $src = $op.original_path

        if (-not (Test-Path -LiteralPath $dst)) {
            $results.failed += @{
                file   = $op.file
                reason = "目标文件不存在: $dst"
            }
            continue
        }

        if (Test-Path -LiteralPath $src) {
            $results.failed += @{
                file   = $op.file
                reason = "原位置已有同名文件: $src"
            }
            continue
        }

        try {
            if (-not $IsDryRun) {
                $srcParent = Split-Path -Path $src -Parent
                if (-not (Test-Path -LiteralPath $srcParent)) {
                    New-Item -ItemType Directory -Path $srcParent -Force | Out-Null
                }
                Move-Item -LiteralPath $dst -Destination $src -Force
            }
            $results.restored += @{
                file   = $op.file
                from   = $dst
                to     = $src
                status = if ($IsDryRun) { "dry_run" } else { "done" }
            }
        } catch {
            $results.failed += @{
                file   = $op.file
                reason = $_.Exception.Message
            }
        }
    }

    # Clean up empty auto-created folders
    foreach ($folderInfo in $logContent.created_folders) {
        $folderPath = $folderInfo.path
        if ((Test-Path -LiteralPath $folderPath) -and (Test-Path -LiteralPath $folderPath -PathType Container)) {
            try {
                # Get ALL items including system+hidden (desktop.ini etc.)
                $remaining = @(Get-ChildItem -LiteralPath $folderPath -Force -ErrorAction SilentlyContinue)
                # Only count user-created files (exclude system files like desktop.ini)
                $systemNames = @("desktop.ini", "Thumbs.db", ".DS_Store")
                $realFiles = @($remaining | Where-Object {
                    -not $_.Name.StartsWith(".") -and ($systemNames -notcontains $_.Name)
                })
                if ($realFiles.Count -eq 0) {
                    if (-not $IsDryRun) {
                        # Remove all remaining items (hidden/system files) first
                        foreach ($hf in $remaining) {
                            # Clear System+Hidden+ReadOnly attributes before removal
                            try {
                                $hf.Attributes = [System.IO.FileAttributes]::Normal
                            } catch {}
                            Remove-Item -LiteralPath $hf.FullName -Force -ErrorAction SilentlyContinue
                        }
                        # Remove the folder itself, also clear its attributes first
                        try {
                            $dirInfo = Get-Item -LiteralPath $folderPath -Force
                            $dirInfo.Attributes = [System.IO.FileAttributes]::Directory
                        } catch {}
                        Remove-Item -LiteralPath $folderPath -Force -Recurse
                    }
                    $results.cleaned_folders += @{
                        folder = $folderInfo.folder_name
                        path   = $folderPath
                        status = if ($IsDryRun) { "dry_run" } else { "removed" }
                    }
                }
            } catch {
                $results.failed += @{
                    file   = $folderInfo.folder_name
                    reason = "清理空文件夹失败: $($_.Exception.Message)"
                }
            }
        }
    }

    $results | ConvertTo-Json -Depth 10
}

function Invoke-RollbackSingle {
    param([string]$LogFilePath, [string]$TargetFileName, [bool]$IsDryRun)

    $logFile = Resolve-Path -LiteralPath $LogFilePath -ErrorAction Stop
    if (-not (Test-Path -LiteralPath $logFile)) {
        @{ error = "Log file not found: $logFile" } | ConvertTo-Json -Depth 5
        exit 1
    }

    $logContent = Get-Content -LiteralPath $logFile -Raw -Encoding UTF8 | ConvertFrom-Json

    $results = @{
        rollback_log    = $logFile.ToString()
        target_file     = $TargetFileName
        dry_run         = $IsDryRun
        restored        = @()
        failed          = @()
        cleaned_folders = @()
    }

    $targetOp = $null
    foreach ($op in $logContent.operations) {
        if ($op.file -eq $TargetFileName) {
            $targetOp = $op
            break
        }
    }

    if (-not $targetOp) {
        $results.failed += @{
            file   = $TargetFileName
            reason = "未在操作日志中找到该文件"
        }
        $results | ConvertTo-Json -Depth 10
        return
    }

    $dst = $targetOp.destination_path
    $src = $targetOp.original_path

    if (-not (Test-Path -LiteralPath $dst)) {
        $results.failed += @{
            file   = $TargetFileName
            reason = "目标文件不存在: $dst"
        }
    } elseif (Test-Path -LiteralPath $src) {
        $results.failed += @{
            file   = $TargetFileName
            reason = "原位置已有同名文件: $src"
        }
    } else {
        try {
            if (-not $IsDryRun) {
                $srcParent = Split-Path -Path $src -Parent
                if (-not (Test-Path -LiteralPath $srcParent)) {
                    New-Item -ItemType Directory -Path $srcParent -Force | Out-Null
                }
                Move-Item -LiteralPath $dst -Destination $src -Force
            }
            $results.restored += @{
                file   = $TargetFileName
                from   = $dst
                to     = $src
                status = if ($IsDryRun) { "dry_run" } else { "done" }
            }
        } catch {
            $results.failed += @{
                file   = $TargetFileName
                reason = $_.Exception.Message
            }
        }
    }

    # Check if folder is now empty and was auto-created
    if ($results.restored.Count -gt 0) {
        $destFolder = Split-Path -Path $dst -Parent
        foreach ($folderInfo in $logContent.created_folders) {
            if ($folderInfo.path -eq $destFolder) {
                if (Test-Path -LiteralPath $destFolder) {
                    $allItems = @(Get-ChildItem -LiteralPath $destFolder -Force -ErrorAction SilentlyContinue)
                    $systemNames = @("desktop.ini", "Thumbs.db", ".DS_Store")
                    $remaining = @($allItems | Where-Object {
                        -not $_.Name.StartsWith(".") -and ($systemNames -notcontains $_.Name)
                    })
                    if ($remaining.Count -eq 0) {
                        try {
                            if (-not $IsDryRun) {
                                foreach ($hf in $allItems) {
                                    try { $hf.Attributes = [System.IO.FileAttributes]::Normal } catch {}
                                    Remove-Item -LiteralPath $hf.FullName -Force -ErrorAction SilentlyContinue
                                }
                                try {
                                    $dirInfo = Get-Item -LiteralPath $destFolder -Force
                                    $dirInfo.Attributes = [System.IO.FileAttributes]::Directory
                                } catch {}
                                Remove-Item -LiteralPath $destFolder -Force -Recurse
                            }
                            $results.cleaned_folders += @{
                                folder = $folderInfo.folder_name
                                path   = $destFolder
                                status = if ($IsDryRun) { "dry_run" } else { "removed" }
                            }
                        } catch {
                            $results.failed += @{
                                file   = $folderInfo.folder_name
                                reason = "清理空文件夹失败: $($_.Exception.Message)"
                            }
                        }
                    }
                }
                break
            }
        }
    }

    $results | ConvertTo-Json -Depth 10
}

function Invoke-ListLogs {
    param([string]$TargetDirPath)

    $logDir = Join-Path (Resolve-Path -LiteralPath $TargetDirPath).Path ".file_organizer_logs"
    if (-not (Test-Path -LiteralPath $logDir)) {
        @{ logs = @(); message = "未找到操作日志目录" } | ConvertTo-Json -Depth 5
        return
    }

    $logs = @()
    $logFiles = Get-ChildItem -LiteralPath $logDir -Filter "organize_*.json" | Sort-Object Name -Descending

    foreach ($f in $logFiles) {
        try {
            $data = Get-Content -LiteralPath $f.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
            $logs += @{
                file             = $f.Name
                path             = $f.FullName
                timestamp        = if ($data.timestamp) { $data.timestamp } else { "unknown" }
                operations_count = @($data.operations).Count
                dry_run          = [bool]$data.dry_run
            }
        } catch {
            $logs += @{
                file  = $f.Name
                path  = $f.FullName
                error = "无法解析"
            }
        }
    }

    @{ logs = $logs } | ConvertTo-Json -Depth 10
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

switch ($Command) {
    "rollback-all" {
        if (-not $LogPath) { Write-Error "rollback-all requires -LogPath"; exit 1 }
        Invoke-RollbackAll -LogFilePath $LogPath -IsDryRun ([bool]$DryRun)
    }
    "rollback-single" {
        if (-not $LogPath) { Write-Error "rollback-single requires -LogPath"; exit 1 }
        if (-not $FileName) { Write-Error "rollback-single requires -FileName"; exit 1 }
        Invoke-RollbackSingle -LogFilePath $LogPath -TargetFileName $FileName -IsDryRun ([bool]$DryRun)
    }
    "list-logs" {
        if (-not $TargetDir) { Write-Error "list-logs requires -TargetDir"; exit 1 }
        Invoke-ListLogs -TargetDirPath $TargetDir
    }
}
